/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todav.core;

public class TodavCore {
    public void initializeDefault() {

    }

    public boolean someLibraryMethod() {
        return true;
    }
}
