/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todav.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TodavCoreTest {
    @Test void someLibraryMethodReturnsTrue() {
        TodavCore classUnderTest = new TodavCore();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
